### ISSUE TITLE
add it to MadeInSenegal ?! 🤔

### ISSUE THREAD

**Issue by daoodaba975** [sissokho/laravel-dev-joke#1]
Hello @sissokho 
Nice job, are you interresed to add it to [Made in Senegal](https://github.com/GalsenDev221/made.in.senegal) ?

We are collecting tools made by senegalese dev !

**Comment by sissokho** [comment]
Hi @daoodaba975,

Of course, I'm interested.

Thank you for reaching out.

**Comment by daoodaba975** [comment]
Great ✨
Looking forward to receiving your contribution

Thx
